{% set name = "brighteyes-ism" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/brighteyes-ism-{{ version }}.tar.gz
  sha256: f615d88349ad7accc522f2bfb55bd25d94c1470916b1ba2bf2d73a4afffbf915

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=61.0
  run:
    - h5py
    - joblib
    - matplotlib-base
    - matplotlib-scalebar
    - numpy
    - poppy
    - pycustomfocus
    - python >=3.7
    - scipy
    - scikit-image
    - scikit-learn
    - statsmodels
    - tqdm

test:
  imports:
    - brighteyes_ism
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/VicidominiLab/brighteyes-ism
  summary: A toolbox for analysing and simulating ISM images
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jaimergp
    - goanpeca
