{% set name = "brighteyes-ism" %}
{% set version = "1.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/brighteyes-ism-{{ version }}.tar.gz
  sha256: c316286d3d3992d72ddc5dc27b087633e3720b8833095d4a8459c00431748047

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=61.0
  run:
    - h5py
    - joblib
    - matplotlib-base
    - matplotlib-scalebar
    - numpy
    - poppy
    - pycustomfocus
    - python >=3.7
    - scipy
    - scikit-image
    - scikit-learn
    - statsmodels
    - tqdm

test:
  imports:
    - brighteyes_ism
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/brighteyes-ism
  summary: A toolbox for analysing and simulating ISM images
  license: GPL-3.0-or-later
  license_file: LICENSE
  dev_url: https://github.com/VicidominiLab/brighteyes-ism

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
