{% set name = "brighteyes-ism" %}
{% set version = "1.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ad52c21103dec9aa4c47b265cac78c60d0b10f1037f56e0e9ecee61061ac668d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=61.0
  run:
    - h5py
    - joblib
    - matplotlib-base
    - matplotlib-scalebar
    - numpy
    - poppy
    - pycustomfocus <=2.3  # See: https://github.com/VicidominiLab/BrightEyes-ISM/issues/3
    - python >=3.7
    - scipy
    - scikit-image
    - scikit-learn
    - statsmodels
    - tqdm

test:
  imports:
    - brighteyes_ism
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/brighteyes-ism
  summary: A toolbox for analysing and simulating ISM images
  license: GPL-3.0-or-later
  license_file: LICENSE
  dev_url: https://github.com/VicidominiLab/brighteyes-ism

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
