{% set name = "brighteyes-ism" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/brighteyes-ism-{{ version }}.tar.gz
  sha256: deef8b297e01e58f92780465a776f0f3b04c54fa45cd171470d497b5a8e80312

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=61.0
    - pip
  run:
    - python >=3.7
    - numpy
    - scipy
    - scikit-image
    - scikit-learn
    - matplotlib-base
    - joblib
    - poppy
    - pycustomfocus
    - tqdm
    - h5py
    - statsmodels

test:
  imports:
    - brighteyes_ism
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/VicidominiLab/brighteyes-ism
  summary: A toolbox for analysing and simulating ISM images
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jaimergp
    - goanpeca
